### ISSUE TITLE
How can handle two database?

### ISSUE THREAD

**Issue by ashokavarthanan** [stefalda/sqlite_wrapper#1]
Hi I tried with two database. its complicated. 
Please example for this.

My database concept is.
      final dbname = 'todo.db';
      final dbname2 = 'store.db';
database 1 is create. using "SQLiteWrapper().openDB"
database 2 is copy from external storage. using "await fromSourcepath.copy(topath);"

Thanks.

**Comment by stefalda** [comment]
Hi,
When you open each db pass the dbName parameter:
const dbName = "TESTDB";
    SQLiteWrapper().openDB(path, dbName: dbName);

Then you can pass the same parameter (dbName) on each call...

Let me know if this explaination is enough...

Stefano

**Comment by ashokavarthanan** [comment]
can u try this? i tried got error "database openDB not....".
can u show a example?

```
E/flutter (14445): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a 
subtype of type 'Database'
E/flutter (14445): #0      SQLiteWrapperCore._getDB (package:sqlite_wrapper/sqlite_wrapper_core.dart:353:16)
E/flutter (14445): #1      SQLiteWrapperCore.query (package:sqlite_wrapper/sqlite_wrapper_core.dart:159:31)     
E/flutter (14445): #2      DatabaseHelper.test (package:sqlite_wrapper_sample/database_helper.dart:58:33) 
```

database_helper.dart line 58
`return await SQLiteWrapper().query("SELECT * FROM message",dbName: dbname3);`

Single database works fine.

**Comment by stefalda** [comment]
Hi,
When you open each db pass the dbName parameter:
const dbName = "TESTDB";
    SQLiteWrapper().openDB(path, dbName: dbName);

Then you can pass the same parameter (dbName) on each call...

Let me know if this explaination is enough...

Stefano

**Comment by stefalda** [comment]
I'm without a PC at the moment but on Tuesday I'll give you a sample...

Have you called openDB with both the dbName before making the query?

**Comment by ashokavarthanan** [comment]
yes I called openDB with dbName1 and dbName2.

**Comment by stefalda** [comment]
Hi,
 this is some working code...

Pay attention to the DB Path because if the DB is not found it is created empty and you would get exactly your error,  when trying to access it...

```dart
import 'package:sqlite_wrapper/sqlite_wrapper_core.dart';

void main(List<String> arguments) async {
  final sqliteWrapper = SQLiteWrapperCore();
  // Open DB 1
  final dbInfo1 = await sqliteWrapper.openDB("./db1.sqlite", dbName: "DB1");
  print("dbInfo1: ${dbInfo1.path}");
  final count1 = await sqliteWrapper.query("SELECT COUNT(*) from table1",
      dbName: "DB1", singleResult: true);
  print('Table1 in DB1 has: $count1 records');
  // Open DB 2
  final dbInfo2 = await sqliteWrapper.openDB("./db2.sqlite", dbName: "DB2");
  print("dbInfo2: ${dbInfo2.path}");
  final count2 = await sqliteWrapper.query("SELECT COUNT(*) from table1",
      dbName: "DB2", singleResult: true);
  print('Table1 in DB2 has: $count2 records');
}
```

I've tested it under windows in pure Dart...

Let me know...

Stefano

**Comment by ashokavarthanan** [comment]
is this working code?
I think its not solved.
ok in your example app runs ok.
when i just add '**dbName: "todoDatabase.sqlite**"'  or  '**dbName: "todoDatabase"**' in **getTodos()** fun.
its not working.
.
**Error:**
`E/flutter (25129): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'Database'
E/flutter (25129): #0      SQLiteWrapperCore._getDB (package:sqlite_wrapper/sqlite_wrapper_core.dart:353:16)
E/flutter (25129): #1      SQLiteWrapperCore.query (package:sqlite_wrapper/sqlite_wrapper_core.dart:159:31)
E/flutter (25129): #2      SQLiteWrapperCore._updateStream (package:sqlite_wrapper/sqlite_wrapper_core.dart:320:29)
E/flutter (25129): #3      SQLiteWrapperCore.updateStreams (package:sqlite_wrapper/sqlite_wrapper_core.dart:334:17)`

**Comment by stefalda** [comment]
dbName is just a string that identifies the DB (a key in a map of dbs)

I guess your problem is linked to the position of the DB, maybe it's not copied in the position where it's read... take a look to the simulator files to understand what's happening...

I hope this helps.

Stefano
