### ISSUE TITLE
Use fromJson/toJsom instead of fromMap/toMap

### ISSUE THREAD

**Issue by rhc** [stefalda/sqlite_wrapper#2]
Hi @stefalda,

Packages like Json_Serializable or Freeze models generally convert models to/from JSON. Is it possible to use those methods instead of to/from Map, as shown in your example?

**Comment by stefalda** [comment]
Hi,
 yes as long as it returns or expects a MAP I don't see any problem...

Let me know if it works.

Thank you

Stefano
