### ISSUE TITLE
version solving failed.

### ISSUE THREAD

**Issue by huanguan1978** [stefalda/sqlite_wrapper#3]
dart pub add sqlite_wrapper
Because every version of sqlite_wrapper depends on sqlite3 ^1.7.1 and demo depends on sqlite3 ^2.2.0, sqlite_wrapper is forbidden.
So, because demo depends on sqlite_wrapper any, version solving failed.

**Comment by stefalda** [comment]
Hi,
 I've reviewed dependencies and compiled with latest Flutter.
