### ISSUE TITLE
Delete with multiple primary keys

### ISSUE THREAD

**Issue by MihaiCraciun88** [stefalda/sqlite_wrapper#4]
Hi,

I got a issue when I used the lib with a table with multiple primary keys.
You have delete function:

` 
  Future<int> delete(Map<String, dynamic> map, String table,
      {required List<String> keys, String? dbName}) async {
...
    for (String key in keys) {
      if (whereClause.isNotEmpty) whereClause += ", ";
      whereClause += "$key=?";
      params.add(map[key]);
    }
...
  }`

If you have SQLiteWrapper().delete(data, 'company_users', ['comp_id', 'user_id']) you get

`DELETE FROM company_users WHERE comp_id=?, user_id=?`
instead of 
`DELETE FROM company_users WHERE comp_id=? AND user_id=?`

Thanks!

**Comment by stefalda** [comment]
You're right, I've fixed the problem and released version 0.1.3
